---
- name: Install poppler-utils
  apt:
    name: [ 'poppler-utils', 'webp' ]
    state: present
    update_cache: no
  become: yes

- name: Create additional /srv/foundry directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "foundry"
    group: "foundry"
    mode: 0555
  become: yes
  with_items:
   - '/srv/foundryVTT/foundrydata/Data/local/pdf'

- name: Create document directories /srv/foundry directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "foundry"
    group: "foundry"
    mode: 0777
  become: yes
  with_items:
   - '/srv/foundryVTT/foundrydata/Data/local/pdf/convert'
   - '/srv/foundryVTT/foundrydata/Data/local/pdf/converted'
   - '/srv/foundryVTT/foundrydata/Data/local/pdf/images'

- name: Create bin-directory
  file:
    path: "/home/{{ item.name }}/bin"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0755
  become: yes
  with_items:
    - "{{ admin_users }}"

- name: Copy convert_pdf.sh
  copy:
    src: "convert_pdf.sh"
    dest: "/home/{{ item.name }}/bin/convert_pdf.sh"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0744'
  become: yes
  with_items:
    - "{{ admin_users }}"

- name: Copy cleanup_pdfextract.sh
  copy:
    src: "cleanup_pdfextract.sh"
    dest: "/home/{{ item.name }}/bin/cleanup_pdfextract.sh"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0744'
  become: yes
  with_items:
    - "{{ admin_users }}"

